import './globals.css'

export const metadata = {
  title: 'DevsKonnekt',
  description: 'Generated by create next app',
}
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <body
        className={`${inter.className} bg-background max-w-7xl w-full mx-auto`}
      >
        {children}
      </body> 
    </html>
  );
}
