name: ESLint

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint and Airbnb config
        run: |
          npm install eslint@8.10.0
          npx install-peerdeps --dev eslint-config-airbnb@18.2.1

      - name: Run ESLint
        run: npx eslint .
          --ext .js,.jsx,.ts,.tsx
          --format json > eslint-results.json

      - name: Comment on ESLint failure
        uses: ataylorme/eslint-annotate-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          results-file: eslint-results.json

      - name: Comment on successful ESLint check
        uses: actions/github-script@v4
        if: ${{ success() }}
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ESLint check passed successfully.'
            })
