name: ESLint

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint and Airbnb config
        run: |
          npm install eslint@8.10.0
          npm install eslint-config-airbnb@latest eslint@latest eslint-plugin-import@latest eslint-plugin-jsx-a11y@latest eslint-plugin-react@latest eslint-plugin-react-hooks@latest --save-dev
      - name: Format Code with Prettier and Lint with Eslint (Frontend)
        run: |
          cd ./Frontend
          npm install
          npm run format
          npm run lint

        continue-on-error: true

      - name: Format Code and Lint with Eslint (Backend)
        run: |
          cd ../Backend
          npm install
          npm run lint:fix
